name: Build-Nusight

on:
  push:
    branches: [ 'master' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    
    - name: Parse markdown
      working-directory: ./Blogs
      run: | 
        dotnet tool install --global MD-Gist
        md-gist parse -t=${{secrets.GIST_TOKEN}}